[project]
name = "susi-26"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Your Name", email = "your.email@example.com" }]
requires-python = ">=3.14"
dependencies = [
    "altair[all]>=6.0.0",
    "jax>=0.10.1",
    "jaxtyping>=0.3.10",
    "matplotlib>=3.10.8",
    "netcdf4>=1.7.4",
    "numba>=0.64.0",
    "numpy>=2.4.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "pareto-dp>=0.1.7",
    "pydantic>=2.12.5",
    "pyproj>=3.7.2",
    "rasterio>=1.4.4",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "shapely>=2.1.2",
    "streamlit>=1.19.0",
    "streamlit-tree-select>=0.0.5",
    "tqdm>=4.67.3",
    "xlrd>=2.0.2",
]
[dependency-groups]
dev = [
    "griffe-pydantic>=1.3.1",
    "hypothesis>=6.152.9",
    "mkdocstrings[python]>=1.0.4",
    "pytest>=9.0.2",
    "xmltodict>=1.0.4",
    "zensical>=0.0.33",
]


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["susi*", "analysis*"]
namespaces = false

[project.scripts]
susi-analyze = "analysis.gui.__main__:main"

[tool.ty.src]
include = ["src", "tests", "src/susi/core/main.py"]
exclude = [
    "src/susi/core/allometric_road_map.py",
    "src/susi/core/allometry.py",
    "src/susi/core/canopygrid.py",
    "src/susi/core/canopylayer.py",
    "src/susi/core/esom.py",
    "src/susi/core/fertilization.py",
    "src/susi/core/gvegetation.py",
    "src/susi/core/methane.py",
    "src/susi/core/mosslayer.py",
    "src/susi/core/stand.py",
    "src/susi/core/stem_curve.py",
    "src/susi/core/strip.py",
    "src/susi/core/susi_utils.py",
    "src/susi/core/temperature.py",
    "src/susi/core/weibull_recovery.py",
    "src/susi/io/susi_io.py",
    "src/scripts/susi_calls_scenarios.py",
    "src/inputs/susi_para.py",
    "src/susi/core/metsi/naslund.py",
    "src/susi/core/thinning_models.py",
    "src/analysis/scrapbook.py",
    "src/analysis/figures.py",
]


[tool.ruff.lint]
ignore = ["F722"]          # Supresses annoying errors with jaxtyping
select = ["F", "W", "ARG"] # Include warnings and checks for function arguments

exclude = ["src/analysis/figures.py", "src/analysis/scrapbook.py"]
[tool.pytest]
# Name of the folders in which to look for tests.
testpaths = ["tests"]

# Ignore the golden file test by default.
# Run with pytest tests/golden_file_test/test_golden_file.py
addopts = [
    "--doctest-modules",
    "--ignore=tests/golden_file_test/test_golden_file.py",
]
