"""
Stand-area lookup for the optimization.

The optimization combines whole stands into project-level totals, so every
stand needs an area in hectares: SUSI's outputs are per-hectare, and
`core.build_optimization_array` multiplies each stand's aggregated target
variables by its area before the stands are summed against each other.

Areas can currently only be sourced for one project, Paroninkorpi, from a
JSON file derived from that site's XML stand export. Generalizing this is
#216. Until that lands, this module is the single place both frontends (the
Streamlit page and the notebook) go for areas, so #216 has exactly one
function body to replace rather than a lookup duplicated per frontend.
"""

from pathlib import Path

import susi.io.load_output_data as load_output
from susi.io.app_settings import AppSettings
from susi.io.load_output_data import StandID
from susi.io.utils import read_json_file

# The only project whose stand areas can be resolved today (see #216).
# Matched against the project folder's path, the way the Streamlit page has
# always done it.
_PARONINKORPI_PROJECT_NAME = "paroninkorpi"

# Paroninkorpi's areas live in the JSON produced alongside its XML-derived
# allometry. Kept relative and resolved against the repo root at call time
# (rather than as an import-time constant) so that merely importing this
# module never touches AppSettings or the filesystem.
#
# Note this folder is untracked user data: it is gitignored, so the path only
# resolves on a machine where that data has actually been generated.
#
_PARONINKORPI_AREAS_JSON_RELPATH = Path("xmltoallometry_with_areas/extra_xml_info.json")


def stand_areas_for_project(project_dirpath: Path) -> dict[StandID, float]:
    """
    Return the area in hectares of every stand in a project output folder.

    project_dirpath is a project folder holding one subfolder per stand --
    e.g. `outputs/paroninkorpi`, the `.value` of a project-level
    `folder_selection.build_dropdown()`. Stand IDs are taken from those
    subfolders, so the result covers exactly the stands the optimization
    will later iterate over.

    Raises ValueError for any project other than Paroninkorpi: there is no
    general way to source stand areas yet (#216), and silently guessing them
    would produce a plausible-looking but wrong Pareto front.
    """
    if _PARONINKORPI_PROJECT_NAME not in str(project_dirpath).lower():
        raise ValueError(
            f"Cannot determine stand areas for project {project_dirpath}. "
            f"Only '{_PARONINKORPI_PROJECT_NAME}' projects are supported so "
            "far; sourcing areas for any other project is issue #216."
        )

    return _read_paroninkorpi_stand_areas(project_dirpath=project_dirpath)


def _read_paroninkorpi_stand_areas(project_dirpath: Path) -> dict[StandID, float]:
    """Read Paroninkorpi's areas file and map it onto project_dirpath's stands."""
    areas_json_path = AppSettings().project_root_path / _PARONINKORPI_AREAS_JSON_RELPATH
    if not areas_json_path.exists():
        raise FileNotFoundError(
            f"Paroninkorpi stand-area file not found: {areas_json_path}. It is "
            "untracked user data, generated by the xml-to-allometry tooling, "
            "so a fresh checkout (or a machine such as CSC) will not have it."
        )

    stand_datas = read_json_file(path=areas_json_path)["stand_datas"]
    stand_ids = [
        StandID(stand_dirpath.name)
        for stand_dirpath in load_output.list_subdirectories_sorted(
            path=project_dirpath
        )
    ]
    return areas_from_stand_datas(stand_datas=stand_datas, stand_ids=stand_ids)


def areas_from_stand_datas(
    stand_datas: dict, stand_ids: list[StandID]
) -> dict[StandID, float]:
    """
    Pick the area of each of stand_ids out of a `stand_datas` mapping.

    stand_datas is the `"stand_datas"` entry of Paroninkorpi's
    extra_xml_info.json: stand number (as a string) -> stand properties,
    one of which is `"area"`, in hectares.

    Split out from the file reading above so it can be unit-tested: the JSON
    itself is untracked user data and so cannot be relied on in tests.

    Raises ValueError, naming the stand, if a stand has no entry -- better
    than a bare KeyError surfacing later, deep inside
    `core.build_optimization_array`.
    """
    areas_ha: dict[StandID, float] = {}
    for stand_id in stand_ids:
        stand_number = _stand_id_to_stand_number(stand_id=stand_id)
        if str(stand_number) not in stand_datas:
            raise ValueError(
                f"No area found for {stand_id} (stand number {stand_number}) "
                "in the Paroninkorpi stand-area file."
            )
        areas_ha[stand_id] = float(stand_datas[str(stand_number)]["area"])
    return areas_ha


def _stand_id_to_stand_number(stand_id: StandID) -> int:
    """
    Turn a stand folder name into the stand number the areas file is keyed by.

    Stand folders are named `stand_<n>` (e.g. `stand_12` -> 12), while the
    XML-derived file keys stands by bare number.
    """
    trailing_part = str(stand_id).split("_")[-1]
    try:
        return int(trailing_part)
    except ValueError as error:
        raise ValueError(
            f"Cannot read a stand number out of the folder name '{stand_id}'; "
            "stand folders are expected to be named 'stand_<number>'."
        ) from error
