import pytest
from pydantic import ValidationError
from susi.core.fertilization import (
    NO_EFFECT,
    fertilization_effect_in_year,
)
from susi.io.susi_parameter_model import (
    StandardNPKFertilizationParameters,
    NutrientFertilizationParameters,
    AshFertilizationParameters,
    FertilizationParameters,
)


# ---------------------------------------------------------------------------
# Pinned values
#
# Characterization tests: they record the values the current implementation
# produces, so that a refactor can be shown to change nothing. The expected
# numbers were generated by running `effect_as_floats` and pasting the `repr`
# of each float.
#
# They are compared with `pytest.approx(rel=PINNED_REL)`, not `==`. Bit-for-bit
# equality only holds on the machine that generated them: on CI's CPU, NumPy's
# exp/power give results that differ in the last digit (~1e-15 relative).
# 1e-12 ignores that noise but still catches any real change to the formulas.
#
# `effect_as_floats` is the only place that knows the fertilization API. When
# the API changes, only the helper changes, never a pinned number.
# ---------------------------------------------------------------------------

PINNED_REL = 1e-12


def effect_as_floats(
    params: FertilizationParameters, year: int
) -> tuple[float, float, float, float]:
    """(pH_increment, N, P, K) for one year, as plain floats."""
    effect = fertilization_effect_in_year(params, year)
    return (
        float(effect.pH_increment),
        float(effect.N_release),
        float(effect.P_release),
        float(effect.K_release),
    )


# The closed form, with all three nutrients different.
FIRST_ORDER_DECAY = StandardNPKFertilizationParameters(
    application_year=2005,
    pH_increment=1.5,
    N=NutrientFertilizationParameters(dose=100.0, decay_k=0.3, eff=0.8),
    P=NutrientFertilizationParameters(dose=40.0, decay_k=0.2, eff=1.0),
    K=NutrientFertilizationParameters(dose=60.0, decay_k=0.5, eff=0.9),
)

# The K storage runs out in 2013: `min(dK, K_storage)` trims that year's release
# to 0.1473, so 2014 is the first year with zero K. P is also fully released
# by the end of 2013.
ASH_K_RUNS_OUT = AshFertilizationParameters(
    application_year=2005,
    fertilizer_dose=3000.0,
    K_in_ash=5.0,
    P_in_ash=2.0,
    time_exp=2.0,
)

# Same as above but dissolving 20x faster: the ash dissolves completely during
# 2015, so `min(dm, mass)` caps the pH increment at its maximum,
# 3000 * 2.5 / 15000 = 0.5, from 2016 on.
ASH_FULLY_DISSOLVED = AshFertilizationParameters(
    application_year=2005,
    fertilizer_dose=3000.0,
    K_in_ash=5.0,
    P_in_ash=2.0,
    time_exp=2.0,
    dissolution_rate=0.1,
)

# year: (pH_increment, N, P, K)
FIRST_ORDER_DECAY_PINNED = {
    2004: (0.0, 0.0, 0.0, 0.0),
    2005: (1.5, 20.73454234546257, 7.2507698768807245, 21.247344375517798),
    2006: (
        1.3572561270539394,
        15.360526767015319,
        5.936428281693701,
        12.887165801224318,
    ),
    2007: (
        1.2280961296169728,
        11.379358108274182,
        4.860336397664518,
        7.816461175242675,
    ),
    2013: (
        0.6739934461758323,
        1.8809952439730182,
        1.4639051909227536,
        0.38915868692656114,
    ),
    2014: (
        0.6098544896108986,
        1.3934755497508668,
        1.1985441993989534,
        0.23603667511446935,
    ),
    2015: (
        0.5518191617571635,
        1.0323120773299146,
        0.9812849949711531,
        0.14316348027355563,
    ),
    2016: (
        0.49930662554711935,
        0.7647555963157956,
        0.8034082029168563,
        0.08683304013707623,
    ),
    2030: (
        0.1231274979358482,
        0.011467951293443746,
        0.04885530313298783,
        7.918148331527132e-05,
    ),
}

ASH_K_RUNS_OUT_PINNED = {
    2004: (0.0, 0.0, 0.0, 0.0),
    2005: (0.0, 0.0, 0.08100000000000006, 0.21600000000000014),
    2006: (0.0015, 0.0, 0.11658845378625908, 0.3109025434300242),
    2007: (0.0036590454404862765, 0.0, 0.16766378271987156, 0.44710342058632413),
    2013: (0.03369962628144382, 0.0, 0.18022018080203306, 0.14725381547208816),
    2014: (0.04093428977043944, 0.0, 0.0, 0.0),
    2015: (0.048674576114955015, 0.0, 0.0, 0.0),
    2016: (0.056881299734230804, 0.0, 0.0, 0.0),
    2030: (0.20244046690025613, 0.0, 0.0, 0.0),
}

ASH_FULLY_DISSOLVED_PINNED = {
    2004: (0.0, 0.0, 0.0, 0.0),
    2005: (0.0, 0.0, 0.08100000000000006, 0.21600000000000014),
    2006: (0.03, 0.0, 0.11210130615999996, 0.29893681642666653),
    2007: (0.07151900228148149, 0.0, 0.15201049160391228, 0.40536131094376604),
    2013: (0.4416554272177852, 0.0, 0.09773164951411525, 0.26061773203764066),
    2014: (0.47785233444523534, 0.0, 0.055392740923719944, 0.14771397579658652),
    2015: (0.4983681644169835, 0.0, 0.010439698773460042, 0.027839196729226776),
    2016: (0.5, 0.0, 0.0, 0.0),
    2030: (0.5, 0.0, 0.0, 0.0),
}


@pytest.mark.parametrize("year, expected", FIRST_ORDER_DECAY_PINNED.items())
def test_pinned_first_order_decay(year: int, expected: tuple[float, ...]):
    assert effect_as_floats(FIRST_ORDER_DECAY, year) == pytest.approx(
        expected, rel=PINNED_REL
    )


@pytest.mark.parametrize("year, expected", ASH_K_RUNS_OUT_PINNED.items())
def test_pinned_ash_K_runs_out(year: int, expected: tuple[float, ...]):
    assert effect_as_floats(ASH_K_RUNS_OUT, year) == pytest.approx(
        expected, rel=PINNED_REL
    )


@pytest.mark.parametrize("year, expected", ASH_FULLY_DISSOLVED_PINNED.items())
def test_pinned_ash_fully_dissolved(year: int, expected: tuple[float, ...]):
    assert effect_as_floats(ASH_FULLY_DISSOLVED, year) == pytest.approx(
        expected, rel=PINNED_REL
    )


# ---------------------------------------------------------------------------
# Behavior
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("year", [1900, 2004, 2005, 2006, 2100])
def test_no_fertilization_has_no_effect_in_any_year(year: int):
    assert fertilization_effect_in_year(None, year) == NO_EFFECT


@pytest.mark.parametrize(
    "params", [FIRST_ORDER_DECAY, ASH_K_RUNS_OUT], ids=["first_order_decay", "ash"]
)
def test_no_effect_before_the_application_year(params: FertilizationParameters):
    year_before = params.application_year - 1
    assert fertilization_effect_in_year(params, year_before) == NO_EFFECT


@pytest.mark.parametrize("years_since_application", [0, 1, 2])
def test_first_order_decay_has_an_effect_from_the_application_year_on(
    years_since_application: int,
):
    effect = fertilization_effect_in_year(
        FIRST_ORDER_DECAY, FIRST_ORDER_DECAY.application_year + years_since_application
    )
    assert effect.pH_increment > 0.0
    assert effect.N_release > 0.0
    assert effect.P_release > 0.0
    assert effect.K_release > 0.0


@pytest.mark.parametrize("years_since_application", [0, 1, 2])
def test_ash_releases_P_and_K_from_the_application_year_on(
    years_since_application: int,
):
    effect = fertilization_effect_in_year(
        ASH_K_RUNS_OUT, ASH_K_RUNS_OUT.application_year + years_since_application
    )
    assert effect.P_release > 0.0
    assert effect.K_release > 0.0


def test_ash_releases_no_N():
    effect = fertilization_effect_in_year(
        ASH_K_RUNS_OUT, ASH_K_RUNS_OUT.application_year + 1
    )
    assert effect.N_release == 0.0


def test_ash_pH_increment_starts_the_year_after_application():
    """
    Start-of-year convention: the pH increment uses the ash dissolved by the
    start of the year, so it's 0 in the application year by design.
    """
    year = ASH_K_RUNS_OUT.application_year
    assert fertilization_effect_in_year(ASH_K_RUNS_OUT, year).pH_increment == 0.0
    assert fertilization_effect_in_year(ASH_K_RUNS_OUT, year + 1).pH_increment > 0.0


# ---------------------------------------------------------------------------
# Parameters
#
# Zero values that would break the calculation are rejected, and each pH
# constant that used to be hardcoded changes the output when varied. The
# defaults leave the pinned values above unchanged.
# ---------------------------------------------------------------------------

# Every year from the application year on, far enough to cover the K storage
# running out (2013) in ASH_K_RUNS_OUT.
YEARS_SINCE_APPLICATION = range(0, 31)


def with_changes(
    params: FertilizationParameters, **changes: float
) -> FertilizationParameters:
    """
    A copy of `params` with `changes` applied, validated again.
    `model_copy(update=...)` skips validation, so it can't be used here.
    """
    return type(params).model_validate({**params.model_dump(), **changes})


@pytest.mark.parametrize("field", ["fertilizer_dose", "grain_radius", "density"])
def test_ash_rejects_zero(field: str):
    # A zero dose gives NaN in every year; a zero radius or density divides by zero.
    with pytest.raises(ValidationError):
        with_changes(ASH_K_RUNS_OUT, **{field: 0.0})


@pytest.mark.parametrize(
    "field, release", [("K_in_ash", "K_release"), ("P_in_ash", "P_release")]
)
def test_ash_without_a_nutrient_releases_none_of_it(field: str, release: str):
    # Ash with no K or no P is physically meaningful, so zero is allowed.
    params = with_changes(ASH_K_RUNS_OUT, **{field: 0.0})
    for years_since_application in YEARS_SINCE_APPLICATION:
        year = params.application_year + years_since_application
        effect = fertilization_effect_in_year(params, year)
        assert getattr(effect, release) == 0.0


def test_zero_pH_decay_k_keeps_the_pH_increment_constant():
    params = with_changes(FIRST_ORDER_DECAY, pH_decay_k=0.0)
    for years_since_application in YEARS_SINCE_APPLICATION:
        year = params.application_year + years_since_application
        effect = fertilization_effect_in_year(params, year)
        assert effect.pH_increment == FIRST_ORDER_DECAY.pH_increment


def test_faster_pH_decay_k_gives_a_lower_pH_increment_after_the_application_year():
    faster = with_changes(
        FIRST_ORDER_DECAY, pH_decay_k=2 * FIRST_ORDER_DECAY.pH_decay_k
    )
    # In the application year exp(0) = 1, so the decay rate makes no difference.
    for years_since_application in YEARS_SINCE_APPLICATION[1:]:
        year = FIRST_ORDER_DECAY.application_year + years_since_application
        assert (
            fertilization_effect_in_year(faster, year).pH_increment
            < fertilization_effect_in_year(FIRST_ORDER_DECAY, year).pH_increment
        )


def test_zero_pH_increment_per_dissolved_ash_switches_off_only_the_pH_effect():
    params = with_changes(ASH_K_RUNS_OUT, pH_increment_per_dissolved_ash=0.0)
    for years_since_application in YEARS_SINCE_APPLICATION:
        year = params.application_year + years_since_application
        effect = fertilization_effect_in_year(params, year)
        default_effect = fertilization_effect_in_year(ASH_K_RUNS_OUT, year)
        assert effect.pH_increment == 0.0
        assert effect.P_release == default_effect.P_release
        assert effect.K_release == default_effect.K_release


def test_ash_pH_increment_is_proportional_to_pH_increment_per_dissolved_ash():
    doubled = with_changes(
        ASH_K_RUNS_OUT,
        pH_increment_per_dissolved_ash=2
        * ASH_K_RUNS_OUT.pH_increment_per_dissolved_ash,
    )
    for years_since_application in YEARS_SINCE_APPLICATION:
        year = ASH_K_RUNS_OUT.application_year + years_since_application
        assert fertilization_effect_in_year(
            doubled, year
        ).pH_increment == pytest.approx(
            2 * fertilization_effect_in_year(ASH_K_RUNS_OUT, year).pH_increment
        )
