import json
import warnings
from pathlib import Path

import pytest

import analysis.optimization.stand_areas as stand_areas_module
from analysis.optimization.stand_areas import (
    areas_from_stand_datas,
    stand_areas_for_project,
)
from susi.io.load_output_data import StandID

# Shaped like the "stand_datas" entry of Paroninkorpi's extra_xml_info.json:
# stand number as a string key, and many more properties per stand than the
# area this module cares about.
_STAND_DATAS = {
    "1": {"area": 2.4, "mean_height": 22.1},
    "2": {"area": 1.9, "mean_height": 18.7},
    "10": {"area": 0.5, "mean_height": 20.0},
}


class TestAreasFromStandDatas:
    def test_picks_the_area_of_each_requested_stand(self):
        areas_ha = areas_from_stand_datas(
            stand_datas=_STAND_DATAS,
            stand_ids=[StandID("stand_1"), StandID("stand_10")],
        )

        assert areas_ha == {StandID("stand_1"): 2.4, StandID("stand_10"): 0.5}

    def test_result_is_keyed_by_stand_id_not_by_stand_number(self):
        areas_ha = areas_from_stand_datas(
            stand_datas=_STAND_DATAS, stand_ids=[StandID("stand_2")]
        )

        assert list(areas_ha) == [StandID("stand_2")]

    def test_stand_missing_from_the_file_raises_naming_that_stand(self):
        # A bare KeyError here would otherwise surface much later, inside
        # core.build_optimization_array, with no clue which stand was missing.
        with pytest.raises(ValueError, match="stand_7"):
            areas_from_stand_datas(
                stand_datas=_STAND_DATAS, stand_ids=[StandID("stand_7")]
            )

    def test_stand_folder_not_named_stand_number_raises(self):
        with pytest.raises(ValueError, match="not_a_stand"):
            areas_from_stand_datas(
                stand_datas=_STAND_DATAS, stand_ids=[StandID("not_a_stand")]
            )


class TestStandAreasForProject:
    def test_project_other_than_paroninkorpi_raises_and_points_at_the_issue(self):
        # Sourcing areas for other projects is #216; until then this must
        # fail loudly rather than guess.
        with pytest.raises(ValueError, match="#216"):
            stand_areas_for_project(project_dirpath=Path("outputs/some_other_site"))


class TestReadParoninkorpiStandAreasFilenameFallback:
    """#282: stand_areas_for_project must still work on a project
    directory whose areas file was generated by the pre-#278 tool, which
    wrote the differently-cased extra_XML_info.json."""

    def _patch_repo_root(self, monkeypatch, repo_root_path: Path):
        # Point the repo-root lookup at a tmp_path instead of the real
        # checkout, so the areas file the test writes is the one found.
        monkeypatch.setattr(
            stand_areas_module.io_utils,
            "repo_root",
            lambda: repo_root_path,
        )

    def _make_project_dir(self, tmp_path: Path) -> Path:
        project_dirpath = tmp_path / "paroninkorpi"
        (project_dirpath / "stand_1").mkdir(parents=True)
        return project_dirpath

    def _write_areas_json(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps({"stand_datas": {"1": {"area": 2.4}}}))

    def test_uses_the_current_filename_when_present(self, tmp_path, monkeypatch):
        self._patch_repo_root(monkeypatch, tmp_path)
        self._write_areas_json(
            tmp_path / "xmltoallometry_with_areas" / "extra_xml_info.json"
        )
        project_dirpath = self._make_project_dir(tmp_path)

        areas_ha = stand_areas_module._read_paroninkorpi_stand_areas(
            project_dirpath=project_dirpath
        )

        assert areas_ha == {StandID("stand_1"): 2.4}

    def test_falls_back_to_the_legacy_filename_with_a_warning(
        self, tmp_path, monkeypatch
    ):
        self._patch_repo_root(monkeypatch, tmp_path)
        self._write_areas_json(
            tmp_path / "xmltoallometry_with_areas" / "extra_XML_info.json"
        )
        project_dirpath = self._make_project_dir(tmp_path)

        with pytest.warns(UserWarning, match="extra_XML_info.json"):
            areas_ha = stand_areas_module._read_paroninkorpi_stand_areas(
                project_dirpath=project_dirpath
            )

        assert areas_ha == {StandID("stand_1"): 2.4}

    def test_prefers_the_current_filename_over_the_legacy_one(
        self, tmp_path, monkeypatch
    ):
        self._patch_repo_root(monkeypatch, tmp_path)
        self._write_areas_json(
            tmp_path / "xmltoallometry_with_areas" / "extra_xml_info.json"
        )
        # A stale legacy file with a different value must not be picked up
        # ahead of the current one.
        self._write_areas_json(
            tmp_path / "xmltoallometry_with_areas" / "extra_XML_info.json"
        )
        (tmp_path / "xmltoallometry_with_areas" / "extra_XML_info.json").write_text(
            json.dumps({"stand_datas": {"1": {"area": 99.9}}})
        )
        project_dirpath = self._make_project_dir(tmp_path)

        with warnings.catch_warnings():
            warnings.simplefilter("error")
            areas_ha = stand_areas_module._read_paroninkorpi_stand_areas(
                project_dirpath=project_dirpath
            )

        assert areas_ha == {StandID("stand_1"): 2.4}

    def test_raises_when_neither_filename_exists(self, tmp_path, monkeypatch):
        self._patch_repo_root(monkeypatch, tmp_path)
        project_dirpath = self._make_project_dir(tmp_path)

        with pytest.raises(FileNotFoundError, match="extra_xml_info.json"):
            stand_areas_module._read_paroninkorpi_stand_areas(
                project_dirpath=project_dirpath
            )
